# Generated by Django 4.2.11 on 2024-06-24 15:31

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_alter_account_preferred_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='confirmation_code',
        ),
        migrations.CreateModel(
            name='AccountToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4)),
                ('identifier', models.CharField(blank=True, help_text='The external personal identifier like an ORCID', max_length=200)),
                ('expiry', models.DateTimeField(default=core.models.generate_expiry_date, verbose_name='Expires on')),
                ('expired', models.BooleanField(default=False)),
                ('next_url', models.CharField(blank=True, help_text='The path where the user should be redirected after login', max_length=200)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-expiry'],
                'get_latest_by': 'expiry',
            },
        ),
    ]
